config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Tekwin</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="<%= pages_about_path %>"><i class="mdi-action-view-list"></i></a></li>
      <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
      <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="<%= pages_about_path %>"><i class="mdi-action-view-list"></i></a></li>
      <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
      <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tekwin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header'%>
    <div class="row">
        <div class="col m10 offset-m1">
            <%= yield %>
        </div>
    </div>
</body>
<script>
  $('.button-collapse').sideNav();
</script>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>